{% set version = "1.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-nanonext
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/nanonext_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/nanonext/nanonext_{{ version }}.tar.gz
  sha256: fbe98f998f9d28ae255b56558bfdc7dcad8726ee3cd7a1e7f05a4d91388f1dc8
  patches:
    - 0001-no-static-libs-in-unix.patch
    - 0002-windows-static-lib-in-configure.patch

build:
  merge_build_host: true  # [win]
  missing_dso_whitelist:
    - '*/R.dll'  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib('c') }}
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ posix }}unzip             # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-later
    - nng >=1.7.2
    - mbedtls  # [not win]
    - m2w64-libwinpthread-git  # [win]
  run:
    - r-base
    - r-later
    - {{ pin_compatible('mbedtls', max_pin='x.x') }}  # [not win]
    - {{ pin_compatible('nng', max_pin='x.x.x') }}  # [not win]
    - {{ pin_compatible('m2w64-libwinpthread-git', max_pin='x.x.x') }}  # [win]
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('nanonext')"           # [not win]
    - "\"%R%\" -e \"library('nanonext')\""  # [win]

about:
  home: https://shikokuchuo.net/nanonext/
  dev_url: https://github.com/shikokuchuo/nanonext/
  license: GPL-3.0-or-later
  summary: R binding for NNG (Nanomsg Next Gen), a successor to ZeroMQ. NNG is a socket library implementing 'Scalability Protocols', a reliable, high-performance standard for common communications patterns including publish/subscribe, request/reply and service discovery, over in-process, IPC, TCP, WebSocket and secure TLS
    transports. As its own threaded concurrency framework, provides a toolkit for asynchronous programming and distributed computing, with intuitive 'aio' objects which resolve automatically upon completion of asynchronous operations, and synchronisation primitives allowing R to wait upon events signalled by concurrent threads.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
    - NNG_LICENSE.txt  # [win]
    - MBEDTLS_LICENSE.txt  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - brendanf

# Package: nanonext
# Type: Package
# Title: NNG (Nanomsg Next Gen) Lightweight Messaging Library
# Version: 0.12.0
# Description: R binding for NNG (Nanomsg Next Gen), a successor to ZeroMQ. NNG is a socket library implementing 'Scalability Protocols', a reliable, high-performance standard for common communications patterns including publish/subscribe, request/reply and service discovery, over in-process, IPC, TCP, WebSocket and secure TLS transports. As its own threaded concurrency framework, provides a toolkit for asynchronous programming and distributed computing, with intuitive 'aio' objects which resolve automatically upon completion of asynchronous operations, and synchronisation primitives allowing R to wait upon events signalled by concurrent threads.
# Authors@R: c(person(given = "Charlie", family = "Gao", role = c("aut", "cre"), email = "charlie.gao@shikokuchuo.net", comment = c(ORCID = "0000-0002-0750-061X")), person(given = "Hibiki AI Limited", role = "cph"), person(given = "R Consortium", role = "fnd"))
# License: GPL (>= 3)
# BugReports: https://github.com/shikokuchuo/nanonext/issues
# URL: https://shikokuchuo.net/nanonext/, https://github.com/shikokuchuo/nanonext/
# Encoding: UTF-8
# SystemRequirements: 'libnng' >= 1.5 and 'libmbedtls' >= 2.5, or 'cmake' to compile NNG and/or Mbed TLS included in package sources
# Depends: R (>= 3.5)
# RoxygenNote: 7.2.3
# Suggests: knitr, markdown
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2024-01-10 14:54:29 UTC; cg334
# Author: Charlie Gao [aut, cre] (<https://orcid.org/0000-0002-0750-061X>), Hibiki AI Limited [cph], R Consortium [fnd]
# Maintainer: Charlie Gao <charlie.gao@shikokuchuo.net>
# Repository: CRAN
# Date/Publication: 2024-01-10 17:23:02 UTC
